### PR TITLE
[FEAT] Add coverage + support for Python 3.10-3.12

### PR DESCRIPTION
**Pull request by bashhack**
## Description

Add coverage + support for the following Python versions:

* 3.10
* 3.11
* 3.12

Documentation, GitHub Actions, test runner (NOTE: `nose` has no support for 3.10+), test suite have been updated as required.

`black` was visible in the dependencies, so I did also format the files changed

### CODE REVIEW

**Comment by bashhack** [comment]
@maxkahan - 👋 Thanks for the great library!

Took a pass here at doing some work to show + demonstrate coverage for library interoperability with Python 3.10, 3.11 and 3.12. 

The required checks in this repository aren't running; however, if you check the link in my fork, we're green ✅ across the board.

I did review the `CONTRIBUTING.md` guidelines, but if I've missed anything you might require to consider my PR, don't hesitate to let me know.

Looking forward to hearing from you - thanks again!

**Comment by bashhack** [comment]
cc @josephnewmark-presence for viz 🫡

**Review by maxkahan — APPROVED** [review]
This all looks fine to me, I'm happy to merge.

**Comment by maxkahan** [comment]
@bashhack I will merge this, but Vonage (who owns OpenTok) has migrated the OpenTok code to the Vonage platform and the [Vonage Video API](https://developer.vonage.com/en/video/overview) will be the long-term future direction for video. New users are no longer able to register for OpenTok, and whilst we're not dropping support, I would strongly urge you to consider migrating to the Vonage Video API.

**Comment by bashhack** [comment]
Noted @maxkahan - thanks so much for the merge and for the context 🤝

**Pull request merged**
